# -*- coding: utf-8 -*-
"""taller3_transmisor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjVstBTVEiNrvHbsBrGJE2duwX8wpYpP
"""

#!pip install paho-mqtt # Install the paho-mqtt package
#!pip install --upgrade paho-mqtt

import paho.mqtt.client as mqtt

# Define the server address and port
server_address = "172.171.224.96"
server_port = 1883

# Create a new MQTT client
client = mqtt.Client()

# Connect to the server
client.connect(server_address, server_port)

"""# Generador mensaje"""

#message = "Milagro. mamiiiiii estoy en googlecolab. Este es un mensaje generado en Google Colab del profe Homero. Saludando por allá a quienes me escuchen"
#message = "Hola soy Diego y esta es la evidencia de la Práctica 3, Grupo B."
message = "Final test, 'Tarea 5' ))OO//M(("

"""# Publicador"""

# Define the topic and message
topic = "MFCtopic"
client.publish(topic,message)

"""# Aqui ocurre la desconexion"""

# Disconnect from the server
client.disconnect()
