# -*- coding: utf-8 -*-
"""EMQX_Diego_David.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1UdDbIifBtQjJ1cCiliQh1wrOmqtHex
"""

# pip install paho-mqtt==1.5.1


"""## Suscriptor desde Google Colab"""

import paho.mqtt.client as mqtt

# llamada en caso de conexión exitosa
def al_conectarse(client, userdata, flags, rc):
    print('Se ha conectado al Broker MQTT y el resultado tiene código: '+str(rc))
# Suscribirse al topico
    client.subscribe('test_IoT/')
# llamada en caso de recibir un mensaje
def al_llegar_mensaje(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))

client = mqtt.Client("misegundaconeccion")

# Especificación para los callbacks
client.on_connect = al_conectarse
client.on_message = al_llegar_mensaje

# Establecimiento de una conexion
client.connect('broker.emqx.io', 1883, 60)

client.loop_forever()